version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      EULA: "TRUE"
      VERSION: "1.16.5"
      TYPE: "FORGE"
      ENABLE_RCON: "true" 
      RCON_PASSWORD: ""
      FORGE_INSTALLER: "forge-1.16.5-36.2.0-installer.jar"
    tty: true
    stdin_open: true
    restart: always
    volumes:
    - ${HOME}/minecraft:/data
