version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.16.5"
    tty: true
    stdin_open: true
    restart: always
    volumes:
    - ${HOME}/minecraft:/data
